// <auto-generated />
using System;
using DigitalwareTest.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DigitalwareTest.Migrations
{
    [DbContext(typeof(DigitalWareContext))]
    [Migration("20210531212928_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DigitalwareTest.Entity.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<int>("edad")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("edad");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            apellido = "Romero",
                            edad = 28,
                            nombre = "Juan carlos"
                        },
                        new
                        {
                            Id = 2,
                            apellido = "freitte",
                            edad = 30,
                            nombre = "Faby alberto"
                        },
                        new
                        {
                            Id = 3,
                            apellido = "Machado Arrieta",
                            edad = 36,
                            nombre = "Cinthia Cristina"
                        },
                        new
                        {
                            Id = 4,
                            apellido = "Machado",
                            edad = 71,
                            nombre = "Cesar"
                        },
                        new
                        {
                            Id = 5,
                            apellido = "Machado",
                            edad = 46,
                            nombre = "Maryory"
                        });
                });

            modelBuilder.Entity("DigitalwareTest.Entity.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("precio");

                    b.Property<int>("productoId")
                        .HasColumnType("int")
                        .HasColumnName("productoId");

                    b.Property<int>("tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("productoId");

                    b.ToTable("inventarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            cantidad = 2,
                            fecha = new DateTime(2021, 5, 31, 16, 29, 28, 203, DateTimeKind.Local).AddTicks(5432),
                            precio = 30000m,
                            productoId = 1,
                            tipo = 0
                        });
                });

            modelBuilder.Entity("DigitalwareTest.Entity.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("clienteId")
                        .HasColumnType("int")
                        .HasColumnName("clienteId");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("precio");

                    b.Property<int>("productoId")
                        .HasColumnType("int")
                        .HasColumnName("productoId");

                    b.HasKey("Id");

                    b.HasIndex("clienteId");

                    b.HasIndex("productoId");

                    b.ToTable("movimientos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            cantidad = 2,
                            clienteId = 5,
                            fecha = new DateTime(2021, 5, 31, 16, 29, 28, 202, DateTimeKind.Local).AddTicks(4332),
                            precio = 30000m,
                            productoId = 1
                        });
                });

            modelBuilder.Entity("DigitalwareTest.Entity.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.ToTable("productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            descripcion = "Televisor 14 pulgadas",
                            precio = 15000m
                        },
                        new
                        {
                            Id = 2,
                            descripcion = "Televisor 18 pulgadas",
                            precio = 19800m
                        },
                        new
                        {
                            Id = 3,
                            descripcion = "Radio",
                            precio = 5000m
                        });
                });

            modelBuilder.Entity("DigitalwareTest.Entity.Inventario", b =>
                {
                    b.HasOne("DigitalwareTest.Entity.Producto", "producto")
                        .WithMany("inventarios")
                        .HasForeignKey("productoId")
                        .HasConstraintName("FK_INVENTARIO_PRODUCTO")
                        .IsRequired();

                    b.Navigation("producto");
                });

            modelBuilder.Entity("DigitalwareTest.Entity.Movimiento", b =>
                {
                    b.HasOne("DigitalwareTest.Entity.Cliente", "cliente")
                        .WithMany("movimientos")
                        .HasForeignKey("clienteId")
                        .HasConstraintName("FK_MOVIMIENTO_CLIENTE")
                        .IsRequired();

                    b.HasOne("DigitalwareTest.Entity.Producto", "producto")
                        .WithMany("movimientos")
                        .HasForeignKey("productoId")
                        .HasConstraintName("FK_MOVIMIENTO_PRODUCTO")
                        .IsRequired();

                    b.Navigation("cliente");

                    b.Navigation("producto");
                });

            modelBuilder.Entity("DigitalwareTest.Entity.Cliente", b =>
                {
                    b.Navigation("movimientos");
                });

            modelBuilder.Entity("DigitalwareTest.Entity.Producto", b =>
                {
                    b.Navigation("inventarios");

                    b.Navigation("movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
